import time
from playwright.sync_api import sync_playwright
import os

def verify_emoji_and_color():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        # Adjust viewport to ensure enough height
        context = browser.new_context(viewport={'width': 1280, 'height': 800})
        page = context.new_page()

        # Load the mocked file
        # Assuming php server is running or we load the static html if needed.
        # Since I cannot run PHP, I will load the static html generated by a helper if available,
        # OR I will assume the environment is set up such that I can just verify the static structure if I save index.php as html.

        # Let's convert index.php to index.html for testing, stripping php tags
        with open('index.php', 'r') as f:
            content = f.read()

        # Simple stripping of PHP tags for visualization
        import re
        content = re.sub(r'<\?php.*?\?>', '', content, flags=re.DOTALL)

        # Inject mock data script to simulate a conversation and scheduled message
        mock_script = """
        <script>
            window.onload = function() {
                // Mock user ID
                window.LOGGED_IN_USER_ID = 1;

                // Simulate showing conversations view
                showView('conversations');

                setTimeout(() => {
                    // Simulate selecting a conversation
                    currentConversationId = 1;
                    document.getElementById('message-view-placeholder').classList.add('hidden');
                    document.getElementById('message-view-content').classList.remove('hidden');
                    document.getElementById('chat-partner-name').textContent = 'Test User';

                    // Inject a scheduled message to verify color
                    const container = document.getElementById('message-container');
                    container.innerHTML = '';
                    const msg = {
                        id: 999,
                        content: 'This is a scheduled message test.',
                        sender_type: 'agent',
                        created_at: '2025-01-01 12:00:00',
                        status: 'scheduled',
                        scheduled_at: '2025-01-02 09:00:00'
                    };
                    container.appendChild(createMessageElement(msg));

                    // Trigger Emoji Picker
                    // We need to wait for EmojiButton to be initialized
                    if (!isEmojiPickerInitialized) {
                        initEmojiPicker();
                        isEmojiPickerInitialized = true;
                    }

                    const emojiBtn = document.getElementById('emoji-btn');
                    if(emojiBtn) {
                        emojiBtn.click();
                    }
                }, 1000);
            };
        </script>
        """

        # Insert mock script before closing body
        content = content.replace('</body>', mock_script + '</body>')

        with open('verification/emoji_test_v3.html', 'w') as f:
            f.write(content)

        page.goto('file://' + os.path.abspath('verification/emoji_test_v3.html'))

        # Wait for the view to load and script to run
        time.sleep(3)

        # Wait for emoji picker to appear
        try:
            # The library usually creates an element with class .emoji-picker__wrapper or similar attached to body
            # or directly in a popper.
            # Let's wait for a generic selector that looks like the picker
            # EmojiButton v4 uses .emoji-picker
            page.wait_for_selector('.emoji-picker', state='visible', timeout=5000)
            print("Emoji picker found and visible!")
        except Exception as e:
            print(f"Emoji picker not found or not visible: {e}")

        # Take screenshot
        page.screenshot(path='verification/emoji_and_color_v3.png')

        browser.close()

if __name__ == "__main__":
    verify_emoji_and_color()
