<?php
// Fatal Error Handler
register_shutdown_function(function() {
    $error = error_get_last();
    if ($error !== null && in_array($error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR])) {
        http_response_code(500);
        header('Content-Type: text/html');
        echo "<h1>Fatal Error</h1>";
        echo "<p>" . htmlspecialchars($error['message']) . "</p>";
        echo "<p>File: " . htmlspecialchars($error['file']) . " on line " . $error['line'] . "</p>";
    }
});

if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

require_once __DIR__ . '/../vendor/autoload.php';
require_once 'db.php';
require_once 'financial_helpers.php';

if (!isset($_SESSION['user_id'])) {
    http_response_code(403);
    die('Please log in to generate reports.');
}

$year = $_GET['year'] ?? date('Y');

// Capture Manual Inputs
$manual_inputs = [
    'interest_expense' => isset($_GET['interest_expense']) ? floatval($_GET['interest_expense']) : 0,
    'bank_loans' => isset($_GET['bank_loans']) ? floatval($_GET['bank_loans']) : 0,
    'share_capital' => isset($_GET['share_capital']) ? floatval($_GET['share_capital']) : 0
];

class FinancialPDF extends TCPDF {
    public $business_name;
    public $business_address;
    public $logo_path;

    public function Header() {
        if (!empty($this->logo_path) && file_exists($this->logo_path)) {
            $this->Image($this->logo_path, 10, 10, 25, '', 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        } elseif (!empty($this->logo_path) && filter_var($this->logo_path, FILTER_VALIDATE_URL)) {
             $this->Image($this->logo_path, 10, 10, 25, '', '', '', 'T', false, 300, '', false, false, 0, false, false, false);
        }

        $this->SetFont('helvetica', 'B', 14);
        $this->SetXY(50, 10);
        $this->Cell(0, 15, $this->business_name, 0, 1, 'R', 0, '', 0);

        $this->SetFont('helvetica', '', 9);
        $this->Cell(0, 5, $this->business_address, 0, 1, 'R', 0, '', 0);
        $this->Cell(0, 5, 'Financial Statement', 0, 1, 'R', 0, '', 0);

        $this->SetLineStyle(array('width' => 1, 'color' => array(124, 58, 237)));
        $this->Line(10, 35, 200, 35);
        $this->SetMargins(10, 40, 10);
    }

    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $this->SetTextColor(128, 128, 128);
        $this->Cell(60, 10, 'Generated by ChatMe System', 0, 0, 'L');
        $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage() . ' of ' . $this->getAliasNbPages(), 0, 0, 'R');
    }
}

try {
    // 1. Fetch Converted Data directly from helper
    $all_financial_data = get_complete_financial_data($year, $manual_inputs);

    // 2. Extract Converted Datasets
    $summary_data = $all_financial_data['summary_data'];
    $balance_sheet_data = $all_financial_data['balance_sheet_data'];
    $cash_flow_data = $all_financial_data['cash_flow_data'];
    // Use the pre-calculated equity data from API instead of recalculating
    $equity_data = $all_financial_data['equity_data'];
    $ppe_details = $all_financial_data['ppe_details']; // Pre-converted
    $investment_details = $all_financial_data['investment_details']; // Pre-converted

    $settings = get_settings();
    $currency = htmlspecialchars($settings['default_currency'] ?? 'TZS');

    $pdf = new FinancialPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->business_name = $settings['business_name'] ?? 'System';
    $pdf->business_address = $settings['business_address'] ?? '';

    $logo_url = $settings['profile_picture_url'] ?? '';
    if (!empty($logo_url) && !filter_var($logo_url, FILTER_VALIDATE_URL)) {
         $fs_path = dirname(__DIR__) . '/' . ltrim($logo_url, '/');
         $pdf->logo_path = file_exists($fs_path) ? $fs_path : dirname(__DIR__) . '/assets/logo.png';
    } else {
         $pdf->logo_path = $logo_url ?: dirname(__DIR__) . '/assets/logo.png';
    }

    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor($pdf->business_name);
    $pdf->SetTitle('Financial Statement ' . $year);
    $pdf->SetAutoPageBreak(TRUE, 20);
    $pdf->AddPage();

    function row($label, $val1, $val2, $is_bold = false, $bg_color = false) {
        $font_weight = $is_bold ? 'font-weight: bold;' : '';
        $bg = $bg_color ? 'background-color: #f9fafb;' : 'background-color: #ffffff;';
        if ($is_bold && !$bg_color) $bg = 'background-color: #ffffff;';

        return '<tr style="' . $bg . '">
                    <td style="border: 1px solid #e5e7eb; ' . $font_weight . ' height: 25px;"> ' . $label . '</td>
                    <td style="border: 1px solid #e5e7eb; text-align: right; ' . $font_weight . '">' . $val1 . '</td>
                    <td style="border: 1px solid #e5e7eb; text-align: right; ' . $font_weight . '">' . $val2 . '</td>
                </tr>';
    }

    $th_style = 'background-color: #7c3aed; color: #ffffff; font-weight: bold; text-align: center; border: 1px solid #7c3aed;';

    $html = '<style>
                h2 { color: #111827; font-family: helvetica; font-size: 14pt; margin-bottom: 10px; }
                h3 { color: #374151; font-family: helvetica; font-size: 11pt; margin-top: 15px; margin-bottom: 5px; }
                table { border-collapse: collapse; width: 100%; font-size: 9pt; }
                th { ' . $th_style . ' padding: 8px; }
                td { padding: 6px; color: #374151; }
             </style>';

    // 1. Statement of Comprehensive Income
    $html .= '<h2>Statement of Comprehensive Income</h2>';
    $html .= '<table cellpadding="5">';
    $html .= '<thead>
                <tr>
                    <th width="50%">Item</th>
                    <th width="25%">' . $year . ' (' . $currency . ')</th>
                    <th width="25%">' . ($year - 1) . ' (' . $currency . ')</th>
                </tr>
              </thead><tbody>';

    $html .= row('Total Revenue (Note 1)', format_accounting_number($summary_data[$year]['total_revenue']), format_accounting_number($summary_data[$year - 1]['total_revenue']), false, false);
    $html .= row('Cost of Goods Sold (COGS) (Note 2)', format_accounting_number($summary_data[$year]['cogs']), format_accounting_number($summary_data[$year - 1]['cogs']), false, true);
    $html .= row('Gross Profit', format_accounting_number($summary_data[$year]['gross_profit']), format_accounting_number($summary_data[$year - 1]['gross_profit']), true, false);
    $html .= row('Operating Expenses (OPEX) (Note 2)', format_accounting_number($summary_data[$year]['opex']), format_accounting_number($summary_data[$year - 1]['opex']), false, true);
    $html .= row('Operating Profit', format_accounting_number($summary_data[$year]['operating_profit']), format_accounting_number($summary_data[$year - 1]['operating_profit']), true, false);
    $html .= row('Depreciation Expense (Note 5)', format_accounting_number($summary_data[$year]['total_depreciation']), format_accounting_number($summary_data[$year - 1]['total_depreciation']), false, true);
    $html .= row('Finance Costs (Interest) (Note 3)', format_accounting_number($summary_data[$year]['interest_expense']), format_accounting_number($summary_data[$year - 1]['interest_expense']), false, false);
    $html .= row('Profit Before Tax', format_accounting_number($summary_data[$year]['profit_before_tax']), format_accounting_number($summary_data[$year - 1]['profit_before_tax']), true, true);
    $html .= row('Income Tax Expense (Note 4)', format_accounting_number($summary_data[$year]['income_tax_expense']), format_accounting_number($summary_data[$year - 1]['income_tax_expense']), false, false);
    $html .= row('Net Profit After Tax', format_accounting_number($summary_data[$year]['net_profit_after_tax']), format_accounting_number($summary_data[$year - 1]['net_profit_after_tax']), true, true);

    $html .= '</tbody></table><br><br>';

    // 2. Statement of Financial Position
    $html .= '<h2>Statement of Financial Position (Balance Sheet)</h2>';
    $html .= '<table cellpadding="5">';
    $html .= '<thead>
                <tr>
                    <th width="50%">Item</th>
                    <th width="25%">' . $year . ' (' . $currency . ')</th>
                    <th width="25%">' . ($year - 1) . ' (' . $currency . ')</th>
                </tr>
              </thead><tbody>';

    $html .= '<tr><td colspan="3" style="background-color: #f3f4f6; font-weight: bold;">ASSETS</td></tr>';
    $html .= row('Property, Plant & Equipment (Net) (Note 5)', format_accounting_number($balance_sheet_data[$year]['net_ppe']), format_accounting_number($balance_sheet_data[$year - 1]['net_ppe']), false, false);
    $html .= row('Financial Investments (Note 7)', format_accounting_number($balance_sheet_data[$year]['financial_investments']), format_accounting_number($balance_sheet_data[$year - 1]['financial_investments']), false, true);
    $html .= row('Accounts Receivable', format_accounting_number($balance_sheet_data[$year]['accounts_receivable']), format_accounting_number($balance_sheet_data[$year - 1]['accounts_receivable']), false, false);

    // Conditionally show Tax Receivable
    if ($balance_sheet_data[$year]['tax_receivable'] > 0 || $balance_sheet_data[$year - 1]['tax_receivable'] > 0) {
        $html .= row('Current Tax Receivable (Note 4)', format_accounting_number($balance_sheet_data[$year]['tax_receivable']), format_accounting_number($balance_sheet_data[$year - 1]['tax_receivable']), false, true);
    }

    $html .= row('Cash and Cash Equivalents', format_accounting_number($balance_sheet_data[$year]['cash_position']), format_accounting_number($balance_sheet_data[$year - 1]['cash_position']), false, false);
    $html .= row('Total Assets', format_accounting_number($balance_sheet_data[$year]['total_assets']), format_accounting_number($balance_sheet_data[$year - 1]['total_assets']), true, true);

    $html .= '<tr><td colspan="3" style="background-color: #f3f4f6; font-weight: bold;">LIABILITIES AND EQUITY</td></tr>';
    $html .= row('Accounts Payable', format_accounting_number($balance_sheet_data[$year]['accounts_payable']), format_accounting_number($balance_sheet_data[$year - 1]['accounts_payable']), false, false);
    $html .= row('Tax Payable (Note 4)', format_accounting_number($balance_sheet_data[$year]['tax_payable']), format_accounting_number($balance_sheet_data[$year - 1]['tax_payable']), false, true);

    // Conditionally show Shareholder Loan
    if ($balance_sheet_data[$year]['shareholder_loan'] > 0 || $balance_sheet_data[$year - 1]['shareholder_loan'] > 0) {
        $html .= row('Shareholder Loan / Short Term Borrowing', format_accounting_number($balance_sheet_data[$year]['shareholder_loan']), format_accounting_number($balance_sheet_data[$year - 1]['shareholder_loan']), false, false);
    }

    $html .= row('Bank Loans / Long Term Liabilities (Note 6)', format_accounting_number($balance_sheet_data[$year]['loans_payable']), format_accounting_number($balance_sheet_data[$year - 1]['loans_payable']), false, true);
    $html .= row('Total Equity', format_accounting_number($balance_sheet_data[$year]['equity']), format_accounting_number($balance_sheet_data[$year - 1]['equity']), false, false);
    $html .= row('Total Liabilities and Equity', format_accounting_number($balance_sheet_data[$year]['total_liabilities_and_equity']), format_accounting_number($balance_sheet_data[$year - 1]['total_liabilities_and_equity']), true, true);

    $html .= '</tbody></table><br><br>';

    $pdf->writeHTML($html, true, false, true, false, '');
    $pdf->AddPage();

    // 3. Cash Flow
    $html = '<h2>Statement of Cash Flows</h2>';
    $html .= '<table cellpadding="5">';
    $html .= '<thead>
                <tr>
                    <th width="50%">Item</th>
                    <th width="25%">' . $year . ' (' . $currency . ')</th>
                    <th width="25%">' . ($year - 1) . ' (' . $currency . ')</th>
                </tr>
              </thead><tbody>';

    $html .= row('Profit Before Tax', format_accounting_number($cash_flow_data[$year]['profit_before_tax']), format_accounting_number($cash_flow_data[$year - 1]['profit_before_tax']), false, false);
    $html .= row('Depreciation Adjustment', format_accounting_number($cash_flow_data[$year]['depreciation_add_back']), format_accounting_number($cash_flow_data[$year - 1]['depreciation_add_back']), false, true);
    $html .= row('Change in Accounts Receivable', format_accounting_number(-$cash_flow_data[$year]['increase_in_ar']), format_accounting_number(-$cash_flow_data[$year - 1]['increase_in_ar']), false, false);
    $html .= row('Change in Accounts Payable', format_accounting_number($cash_flow_data[$year]['increase_in_ap']), format_accounting_number($cash_flow_data[$year - 1]['increase_in_ap']), false, true);
    $html .= row('Tax Paid', format_accounting_number(-$cash_flow_data[$year]['tax_paid']), format_accounting_number(-$cash_flow_data[$year - 1]['tax_paid']), false, false);
    $html .= row('Net Cash from Operating', format_accounting_number($cash_flow_data[$year]['operating_activities']), format_accounting_number($cash_flow_data[$year - 1]['operating_activities']), true, true);

    $html .= row('Net Cash from Investing', format_accounting_number($cash_flow_data[$year]['investing_activities']), format_accounting_number($cash_flow_data[$year - 1]['investing_activities']), true, false);
    $html .= row('Net Cash from Financing', format_accounting_number($cash_flow_data[$year]['financing_activities']), format_accounting_number($cash_flow_data[$year - 1]['financing_activities']), true, true);
    $html .= row('Net Increase in Cash', format_accounting_number($cash_flow_data[$year]['net_increase_in_cash']), format_accounting_number($cash_flow_data[$year - 1]['net_increase_in_cash']), true, false);

    $html .= '</tbody></table><br><br>';

    // 4. Statement of Changes in Equity
    // Use pre-calculated and converted equity data
    $equity_curr = $equity_data[$year];
    $equity_prev = $equity_data[$year - 1];

    $html .= '<h2>Statement of Changes in Equity</h2>';
    $html .= '<table cellpadding="5">';
    $html .= '<thead>
                <tr>
                    <th width="50%">Item</th>
                    <th width="25%">' . $year . ' (' . $currency . ')</th>
                    <th width="25%">' . ($year - 1) . ' (' . $currency . ')</th>
                </tr>
              </thead><tbody>';
    $html .= row('Opening Equity Balance', format_accounting_number($equity_curr['opening_balance']), format_accounting_number($equity_prev['opening_balance']), false, false);
    $html .= row('Net Profit for the Period', format_accounting_number($equity_curr['net_profit']), format_accounting_number($equity_prev['net_profit']), false, true);
    $html .= row('Share Capital Injection', format_accounting_number($equity_curr['share_capital']), format_accounting_number($equity_prev['share_capital']), false, false);
    $html .= row('Closing Equity Balance', format_accounting_number($equity_curr['closing_balance']), format_accounting_number($equity_prev['closing_balance']), true, true);
    $html .= '</tbody></table><br><br>';

    $pdf->writeHTML($html, true, false, true, false, '');
    $pdf->AddPage();

    // 5. Notes
    $html = '<h2>Notes to the Financial Statements</h2>';

    // Note 1: Revenue
    $html .= '<h3>Note 1: Revenue</h3>';
    $html .= '<p>Revenue represents the invoiced value of goods sold and services rendered during the year, net of Value Added Tax (VAT).</p>';
    $html .= '<table cellpadding="5"><thead><tr><th width="70%">Description</th><th width="30%">Amount (' . $currency . ')</th></tr></thead><tbody>';
    $html .= row('Sales / Services Revenue', format_accounting_number($summary_data[$year]['total_revenue']), '', false, false);
    $html .= '</tbody></table>';

    // Note 2: Expenses Breakdown
    $html .= '<h3>Note 2: Operating Expenses Breakdown</h3>';
    $breakdown = $summary_data[$year]['expense_breakdown'] ?? [];
    $html .= '<table cellpadding="5"><thead><tr><th width="70%">Description</th><th width="30%">Amount (' . $currency . ')</th></tr></thead><tbody>';

    if (!empty($breakdown['cogs'])) {
        $html .= '<tr><td colspan="2" style="font-weight:bold;">Cost of Goods Sold (COGS)</td></tr>';
        foreach ($breakdown['cogs'] as $name => $amt) {
            $formatted_name = ucwords(str_replace('_', ' ', $name));
            $html .= row('- ' . htmlspecialchars($formatted_name), format_accounting_number($amt), '', false, false);
        }
    }
    if (!empty($breakdown['opex'])) {
        $html .= '<tr><td colspan="2" style="font-weight:bold;">Operating Expenses (OPEX)</td></tr>';
        foreach ($breakdown['opex'] as $name => $amt) {
            $formatted_name = ucwords(str_replace('_', ' ', $name));
            $html .= row('- ' . htmlspecialchars($formatted_name), format_accounting_number($amt), '', false, false);
        }
    } else {
        $html .= '<tr><td colspan="2">No operating expenses recorded for this period.</td></tr>';
    }
    $html .= '</tbody></table>';

    // Note 3: Finance Costs
    $html .= '<h3>Note 3: Finance Costs</h3>';
    $html .= '<table cellpadding="5"><thead><tr><th width="70%">Description</th><th width="30%">Amount (' . $currency . ')</th></tr></thead><tbody>';
    $html .= row('Interest Expense on Bank Loans', format_accounting_number($summary_data[$year]['interest_expense']), '', false, false);
    $html .= '</tbody></table>';

    // Note 4: Tax
    $html .= '<h3>Note 4: Tax Computation</h3>';
    $html .= '<table cellpadding="5"><thead><tr><th width="70%">Item</th><th width="30%">Amount (' . $currency . ')</th></tr></thead><tbody>';
    $html .= row('Profit Before Tax', format_accounting_number($summary_data[$year]['profit_before_tax']), '', false, false);
    $html .= row('Tax Rate Applied', $summary_data[$year]['tax_rate_used'], '', false, true);

    if ($balance_sheet_data[$year]['tax_receivable'] > 0) {
        $html .= row('Tax Liability (Expense)', '0.00 (Loss Carryforward)', '', true, false);
        $html .= row('Less: Tax Payments Made', format_accounting_number($balance_sheet_data[$year]['prepaid_taxes']), '', false, true);
        $html .= row('Tax Asset Recognized (Receivable)', format_accounting_number($balance_sheet_data[$year]['tax_receivable']), '', true, false);
    } else {
        $html .= row('Tax Liability (Expense)', format_accounting_number($summary_data[$year]['income_tax_expense']), '', true, false);
        $html .= row('Less: Tax Payments Made', format_accounting_number($balance_sheet_data[$year]['prepaid_taxes']), '', false, true);
        $html .= row('Net Tax Payable / (Refundable)', format_accounting_number($balance_sheet_data[$year]['tax_payable']), '', true, false);
    }
    $html .= '</tbody></table>';

    // Note 5: PPE (Using Pre-Converted ppe_details)
    if (!empty($ppe_details[$year])) {
        $html .= '<h3>Note 5: Property, Plant, and Equipment (PPE)</h3>';
        $html .= '<table cellpadding="5"><thead><tr><th width="25%">Category</th><th width="25%">Cost</th><th width="25%">Accum. Dep.</th><th width="25%">NBV</th></tr></thead><tbody>';

        $asset_categories = [];
        foreach ($ppe_details[$year] as $asset) {
            if (!isset($asset_categories[$asset['category']])) {
                $asset_categories[$asset['category']] = ['cost' => 0, 'accumulated_depreciation' => 0, 'nbv' => 0];
            }
            $asset_categories[$asset['category']]['cost'] += $asset['purchase_cost'];
            $asset_categories[$asset['category']]['accumulated_depreciation'] += $asset['accumulated_depreciation'];
            $asset_categories[$asset['category']]['nbv'] += $asset['nbv'];
        }
        foreach ($asset_categories as $category => $values) {
             $html .= '<tr>
                        <td style="border: 1px solid #e5e7eb;">' . htmlspecialchars($category) . '</td>
                        <td style="border: 1px solid #e5e7eb; text-align: right;">' . format_accounting_number($values['cost']) . '</td>
                        <td style="border: 1px solid #e5e7eb; text-align: right;">' . format_accounting_number($values['accumulated_depreciation']) . '</td>
                        <td style="border: 1px solid #e5e7eb; text-align: right;">' . format_accounting_number($values['nbv']) . '</td>
                    </tr>';
        }
        $html .= '</tbody></table>';
    }

    // Note 6: Borrowings
    $html .= '<h3>Note 6: Borrowings</h3>';
    $html .= '<table cellpadding="5"><thead><tr><th width="70%">Description</th><th width="30%">Amount (' . $currency . ')</th></tr></thead><tbody>';
    $html .= row('Bank Loans / Long Term Facilities', format_accounting_number($balance_sheet_data[$year]['loans_payable']), '', false, false);
    if ($balance_sheet_data[$year]['shareholder_loan'] > 0) {
        $html .= row('Shareholder Loan (Short Term Deficit Funding)', format_accounting_number($balance_sheet_data[$year]['shareholder_loan']), '', false, true);
    }
    $html .= '</tbody></table>';

    // Note 7: Financial Investments (Using Pre-Converted investment_details)
    if (!empty($investment_details)) {
        $html .= '<h3>Note 7: Financial Investments</h3>';
        $html .= '<p>Financial assets held at cost (Shares, Bonds, etc.). Not depreciated.</p>';
        $html .= '<table cellpadding="5"><thead><tr><th width="40%">Description</th><th width="30%">Type</th><th width="30%">Cost</th></tr></thead><tbody>';
        foreach ($investment_details as $inv) {
            $html .= '<tr>
                        <td style="border: 1px solid #e5e7eb;">' . htmlspecialchars($inv['description']) . '</td>
                        <td style="border: 1px solid #e5e7eb;">' . htmlspecialchars($inv['investment_type']) . '</td>
                        <td style="border: 1px solid #e5e7eb; text-align: right;">' . format_accounting_number($inv['purchase_cost']) . '</td>
                      </tr>';
        }
        $html .= '</tbody></table>';
    }

    $pdf->writeHTML($html, true, false, true, false, '');

    $pdf->Output('Financial_Statement_' . $year . '.pdf', 'I');

} catch (Throwable $e) {
    http_response_code(500);
    echo "<h1>Error Generating Report</h1>";
    echo "<p>" . htmlspecialchars($e->getMessage()) . "</p>";
    echo "<pre>" . htmlspecialchars($e->getTraceAsString()) . "</pre>";
}

function format_accounting_number($number, $decimals = 2) {
    if (floatval($number) == 0) {
        return '-';
    }
    if ($number < 0) {
        return '(' . number_format(abs($number), $decimals) . ')';
    }
    return number_format($number, $decimals);
}
?>
