<?php
// Fatal Error Handler
register_shutdown_function(function() {
    $error = error_get_last();
    if ($error !== null && in_array($error['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR])) {
        http_response_code(500);
        header('Content-Type: text/html');
        echo "<h1>Fatal Error</h1>";
        echo "<p>" . htmlspecialchars($error['message']) . "</p>";
        echo "<p>File: " . htmlspecialchars($error['file']) . " on line " . $error['line'] . "</p>";
    }
});

if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

require_once __DIR__ . '/../vendor/autoload.php';
require_once 'db.php';
require_once 'financial_helpers.php';

if (!isset($_SESSION['user_id'])) {
    http_response_code(403);
    die('Please log in to generate reports.');
}

$year = $_GET['year'] ?? date('Y');

// Capture Manual Inputs (Assumed Base Currency TZS)
$manual_inputs = [
    'interest_expense' => isset($_GET['interest_expense']) ? floatval($_GET['interest_expense']) : 0,
    'bank_loans' => isset($_GET['bank_loans']) ? floatval($_GET['bank_loans']) : 0,
    'number_of_shares' => isset($_GET['number_of_shares']) ? floatval($_GET['number_of_shares']) : 0,
    'par_value' => isset($_GET['par_value']) ? floatval($_GET['par_value']) : 0
];

$shareholder_name = $_GET['shareholder_name'] ?? '';
$template_color_hex = $_GET['template_color'] ?? '#7c3aed';

// Sanitize Hex Color Input
if (!preg_match('/^#[a-fA-F0-9]{6}$/', $template_color_hex)) {
    $template_color_hex = '#7c3aed'; // Fallback to default Violet
}

// Convert Hex to RGB for TCPDF
list($r, $g, $b) = sscanf($template_color_hex, "#%02x%02x%02x");
$theme_color = [$r, $g, $b];

class FinancialPDF extends TCPDF {
    public $business_name;
    public $business_address;
    public $logo_path;
    public $theme_color;

    public function Header() {
        if (!empty($this->logo_path) && file_exists($this->logo_path)) {
            $this->Image($this->logo_path, 10, 10, 25, '', 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        } elseif (!empty($this->logo_path) && filter_var($this->logo_path, FILTER_VALIDATE_URL)) {
             $this->Image($this->logo_path, 10, 10, 25, '', '', '', 'T', false, 300, '', false, false, 0, false, false, false);
        }

        $this->SetFont('helvetica', 'B', 14);
        $this->SetXY(50, 10);
        $this->Cell(0, 15, $this->business_name, 0, 1, 'R', 0, '', 0);

        $this->SetFont('helvetica', '', 9);
        $this->Cell(0, 5, $this->business_address, 0, 1, 'R', 0, '', 0);
        $this->Cell(0, 5, 'Financial Statements', 0, 1, 'R', 0, '', 0);

        $this->SetLineStyle(array('width' => 1, 'color' => $this->theme_color));
        $this->Line(10, 35, 200, 35);
        $this->SetMargins(10, 40, 10);
    }

    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $this->SetTextColor(128, 128, 128);
        $this->Cell(60, 10, 'Generated by ChatMe System - IFRS Compliant', 0, 0, 'L');
        $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage() . ' of ' . $this->getAliasNbPages(), 0, 0, 'R');
    }
}

try {
    $all_financial_data = get_complete_financial_data($year, $manual_inputs);

    $summary_data = $all_financial_data['summary_data'];
    $balance_sheet_data = $all_financial_data['balance_sheet_data'];
    $cash_flow_data = $all_financial_data['cash_flow_data'];
    $equity_data = $all_financial_data['equity_data'];
    $ppe_movement = $all_financial_data['ppe_movement'];
    $investment_details = $all_financial_data['investment_details'];

    $settings = get_settings();
    $currency = htmlspecialchars($settings['default_currency'] ?? 'TZS');

    $pdf = new FinancialPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf->business_name = $settings['business_name'] ?? 'System';
    $pdf->business_address = $settings['business_address'] ?? '';
    $pdf->theme_color = $theme_color;

    $logo_url = $settings['profile_picture_url'] ?? '';
    if (!empty($logo_url) && !filter_var($logo_url, FILTER_VALIDATE_URL)) {
         $fs_path = dirname(__DIR__) . '/' . ltrim($logo_url, '/');
         $pdf->logo_path = file_exists($fs_path) ? $fs_path : dirname(__DIR__) . '/assets/logo.png';
    } else {
         $pdf->logo_path = $logo_url ?: dirname(__DIR__) . '/assets/logo.png';
    }

    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor($pdf->business_name);
    $pdf->SetTitle('Financial Statements ' . $year);
    $pdf->SetAutoPageBreak(TRUE, 20);

    // PAGE 1: Corporate Info & Directors Report
    $pdf->AddPage();
    $html_intro = '<h1 style="color:'.$template_color_hex.'; text-align:center;">Annual Report and Financial Statements</h1>
    <h2 style="text-align:center;">For the year ended 31 December ' . $year . '</h2>
    <br><br><br>
    <h3>Corporate Information</h3>
    <table cellpadding="5">
        <tr><td width="30%"><b>Business Name:</b></td><td>' . $pdf->business_name . '</td></tr>
        <tr><td><b>Registered Address:</b></td><td>' . $pdf->business_address . '</td></tr>
        <tr><td><b>Tax Identification Number:</b></td><td>' . ($settings['tin_number'] ?? 'N/A') . '</td></tr>
        <tr><td><b>Functional Currency:</b></td><td>' . $currency . '</td></tr>
    </table>
    <br><br>
    <h3>Directors\' Approval Statement</h3>
    <p>The Directors acknowledge their responsibility for the preparation and presentation of the financial statements, which give a true and fair view of the state of affairs of the Company as at 31 December ' . $year . ' and of its profit and cash flows for the year then ended in accordance with International Financial Reporting Standards (IFRS) and the Companies Act.</p>
    <br><br><br><br>
    <table cellpadding="5">
        <tr>
            <td width="50%">_________________________<br><b>Director</b><br>Date: ' . date('d-M-Y') . '</td>
            <td width="50%">_________________________<br><b>Director</b><br>Date: ' . date('d-M-Y') . '</td>
        </tr>
    </table>';
    $pdf->writeHTML($html_intro, true, false, true, false, '');

    // PAGE 2: Significant Accounting Policies
    $pdf->AddPage();
    $html_policies = '<h2 style="color:'.$template_color_hex.';">Significant Accounting Policies</h2>
    <p>The principal accounting policies adopted in the preparation of these financial statements are set out below:</p>
    <ol>
        <li><b>Basis of Preparation:</b> The financial statements have been prepared in accordance with International Financial Reporting Standards (IFRS). They are prepared under the historical cost convention, except for financial assets measured at fair value.</li>
        <br>
        <li><b>Revenue Recognition (IFRS 15):</b> Revenue is recognized when control of the goods or services transfers to the customer at an amount that reflects the consideration to which the entity expects to be entitled in exchange for those goods or services.</li>
        <br>
        <li><b>Property, Plant and Equipment (IAS 16):</b> Items of property, plant and equipment are measured at cost less accumulated depreciation and any accumulated impairment losses. Depreciation is calculated on a pro-rata basis.</li>
        <br>
        <li><b>Financial Instruments (IFRS 9):</b>
            <ul>
                <li><b>Financial Assets:</b> Classified as Financial Assets at Fair Value Through Profit or Loss (FVTPL) or Amortised Cost depending on the business model.</li>
                <li><b>Financial Liabilities:</b> Measured at amortised cost using the effective interest method.</li>
            </ul>
        </li>
        <br>
        <li><b>Taxation (IAS 12):</b> Current tax is the expected tax payable on the taxable income for the year, using tax rates enacted or substantively enacted at the reporting date.</li>
    </ol>';
    $pdf->writeHTML($html_policies, true, false, true, false, '');

    // Styles for Tables
    $th_style = 'background-color: '.$template_color_hex.'; color: #ffffff; font-weight: bold; text-align: center; border: 1px solid '.$template_color_hex.';';
    $html_style = '<style>
        h2 { color: '.$template_color_hex.'; font-family: helvetica; font-size: 14pt; margin-bottom: 10px; }
        h3 { color: #374151; font-family: helvetica; font-size: 11pt; margin-top: 15px; margin-bottom: 5px; }
        table { border-collapse: collapse; width: 100%; font-size: 9pt; }
        th { ' . $th_style . ' padding: 8px; }
        td { padding: 6px; color: #374151; }
    </style>';

    function row($label, $val1, $val2, $is_bold = false, $bg_color = false) {
        $font_weight = $is_bold ? 'font-weight: bold;' : '';
        $bg = $bg_color ? 'background-color: #f9fafb;' : 'background-color: #ffffff;';
        if ($is_bold && !$bg_color) $bg = 'background-color: #ffffff;';

        return '<tr style="' . $bg . '">
                    <td style="border: 1px solid #e5e7eb; ' . $font_weight . ' height: 25px;"> ' . $label . '</td>
                    <td style="border: 1px solid #e5e7eb; text-align: right; ' . $font_weight . '">' . $val1 . '</td>
                    <td style="border: 1px solid #e5e7eb; text-align: right; ' . $font_weight . '">' . $val2 . '</td>
                </tr>';
    }

    // PAGE 3: Income Statement
    $pdf->AddPage();
    $html = $html_style . '<h2>Statement of Comprehensive Income</h2>';
    $html .= '<table cellpadding="5"><thead><tr><th width="50%">Particulars</th><th width="25%">' . $year . ' (' . $currency . ')</th><th width="25%">' . ($year - 1) . ' (' . $currency . ')</th></tr></thead><tbody>';
    $html .= row('Revenue (Note 3)', format_accounting_number($summary_data[$year]['total_revenue']), format_accounting_number($summary_data[$year - 1]['total_revenue']));
    $html .= row('Cost of Sales (Note 4)', format_accounting_number($summary_data[$year]['cogs']), format_accounting_number($summary_data[$year - 1]['cogs']), false, true);
    $html .= row('Gross Profit', format_accounting_number($summary_data[$year]['gross_profit']), format_accounting_number($summary_data[$year - 1]['gross_profit']), true, false);
    $html .= row('Operating Expenses (Note 4)', format_accounting_number($summary_data[$year]['opex']), format_accounting_number($summary_data[$year - 1]['opex']), false, true);
    $html .= row('Operating Profit', format_accounting_number($summary_data[$year]['operating_profit']), format_accounting_number($summary_data[$year - 1]['operating_profit']), true, false);
    $html .= row('Depreciation (Note 6)', format_accounting_number($summary_data[$year]['total_depreciation']), format_accounting_number($summary_data[$year - 1]['total_depreciation']), false, true);
    $html .= row('Finance Costs (Note 9)', format_accounting_number($summary_data[$year]['interest_expense']), format_accounting_number($summary_data[$year - 1]['interest_expense']), false, false);
    $html .= row('Profit Before Tax', format_accounting_number($summary_data[$year]['profit_before_tax']), format_accounting_number($summary_data[$year - 1]['profit_before_tax']), true, true);
    $html .= row('Taxation (Note 5)', format_accounting_number($summary_data[$year]['income_tax_expense']), format_accounting_number($summary_data[$year - 1]['income_tax_expense']), false, false);
    $html .= row('Net Profit', format_accounting_number($summary_data[$year]['net_profit_after_tax']), format_accounting_number($summary_data[$year - 1]['net_profit_after_tax']), true, true);
    $html .= '</tbody></table>';
    $pdf->writeHTML($html, true, false, true, false, '');

    // PAGE 4: Balance Sheet
    $pdf->AddPage();
    $html = $html_style . '<h2>Statement of Financial Position</h2>';
    $html .= '<table cellpadding="5"><thead><tr><th width="50%">Assets</th><th width="25%">' . $year . ' (' . $currency . ')</th><th width="25%">' . ($year - 1) . ' (' . $currency . ')</th></tr></thead><tbody>';

    $html .= '<tr><td colspan="3" style="background-color: #f3f4f6; font-weight: bold;">Non-Current Assets</td></tr>';
    $html .= row('Property, Plant & Equipment (Note 6)', format_accounting_number($balance_sheet_data[$year]['net_ppe']), format_accounting_number($balance_sheet_data[$year - 1]['net_ppe']));
    $html .= row('Financial Investments (Note 7)', format_accounting_number($balance_sheet_data[$year]['financial_investments']), format_accounting_number($balance_sheet_data[$year - 1]['financial_investments']), false, true);

    $html .= '<tr><td colspan="3" style="background-color: #f3f4f6; font-weight: bold;">Current Assets</td></tr>';
    $html .= row('Accounts Receivable', format_accounting_number($balance_sheet_data[$year]['accounts_receivable']), format_accounting_number($balance_sheet_data[$year - 1]['accounts_receivable']));
    if ($balance_sheet_data[$year]['tax_receivable'] > 0 || $balance_sheet_data[$year - 1]['tax_receivable'] > 0) {
        $html .= row('Current Tax Receivable (Note 5)', format_accounting_number($balance_sheet_data[$year]['tax_receivable']), format_accounting_number($balance_sheet_data[$year - 1]['tax_receivable']), false, true);
    }
    $html .= row('Cash and Cash Equivalents', format_accounting_number($balance_sheet_data[$year]['cash_position']), format_accounting_number($balance_sheet_data[$year - 1]['cash_position']), false, true);
    $html .= row('Total Assets', format_accounting_number($balance_sheet_data[$year]['total_assets']), format_accounting_number($balance_sheet_data[$year - 1]['total_assets']), true, true);

    $html .= '<tr><td colspan="3" style="background-color: #f3f4f6; font-weight: bold;">Equity and Liabilities</td></tr>';
    $html .= row('Share Capital & Equity (Note 8)', format_accounting_number($balance_sheet_data[$year]['equity']), format_accounting_number($balance_sheet_data[$year - 1]['equity']));
    $html .= row('Accounts Payable', format_accounting_number($balance_sheet_data[$year]['accounts_payable']), format_accounting_number($balance_sheet_data[$year - 1]['accounts_payable']), false, true);
    $html .= row('Tax Payable (Note 5)', format_accounting_number($balance_sheet_data[$year]['tax_payable']), format_accounting_number($balance_sheet_data[$year - 1]['tax_payable']));
    if ($balance_sheet_data[$year]['shareholder_loan'] > 0 || $balance_sheet_data[$year - 1]['shareholder_loan'] > 0) {
        $html .= row('Shareholder Loan / Short Term Borrowing', format_accounting_number($balance_sheet_data[$year]['shareholder_loan']), format_accounting_number($balance_sheet_data[$year - 1]['shareholder_loan']), false, true);
    }
    $html .= row('Borrowings (Note 9)', format_accounting_number($balance_sheet_data[$year]['loans_payable']), format_accounting_number($balance_sheet_data[$year - 1]['loans_payable']), false, true);
    $html .= row('Total Equity and Liabilities', format_accounting_number($balance_sheet_data[$year]['total_liabilities_and_equity']), format_accounting_number($balance_sheet_data[$year - 1]['total_liabilities_and_equity']), true, true);
    $html .= '</tbody></table>';
    $pdf->writeHTML($html, true, false, true, false, '');

    // PAGE 5: Cash Flow
    $pdf->AddPage();
    $html = $html_style . '<h2>Statement of Cash Flows</h2>';
    $html .= '<table cellpadding="5"><thead><tr><th width="50%">Particulars</th><th width="25%">' . $year . ' (' . $currency . ')</th><th width="25%">' . ($year - 1) . ' (' . $currency . ')</th></tr></thead><tbody>';

    $html .= '<tr><td colspan="3" style="font-weight: bold;">Operating Activities</td></tr>';
    $html .= row('Profit Before Tax', format_accounting_number($cash_flow_data[$year]['profit_before_tax']), format_accounting_number($cash_flow_data[$year - 1]['profit_before_tax']));
    $html .= row('Adjustments for Depreciation', format_accounting_number($cash_flow_data[$year]['depreciation_add_back']), format_accounting_number($cash_flow_data[$year - 1]['depreciation_add_back']), false, true);
    $html .= row('Change in Working Capital (AR/AP)', format_accounting_number(-$cash_flow_data[$year]['increase_in_ar'] + $cash_flow_data[$year]['increase_in_ap']), format_accounting_number(-$cash_flow_data[$year - 1]['increase_in_ar'] + $cash_flow_data[$year - 1]['increase_in_ap']));
    $html .= row('Tax Paid', format_accounting_number(-$cash_flow_data[$year]['tax_paid']), format_accounting_number(-$cash_flow_data[$year - 1]['tax_paid']), false, true);
    $html .= row('Net Cash from Operating Activities', format_accounting_number($cash_flow_data[$year]['operating_activities']), format_accounting_number($cash_flow_data[$year - 1]['operating_activities']), true, false);

    $html .= '<tr><td colspan="3" style="font-weight: bold;">Investing Activities</td></tr>';
    $html .= row('Purchase of PPE (Additions)', format_accounting_number(-$cash_flow_data[$year]['additions_ppe']), format_accounting_number(-$cash_flow_data[$year - 1]['additions_ppe']), false, true);
    $html .= row('Purchase of Financial Investments', format_accounting_number(-$cash_flow_data[$year]['purchase_investments']), format_accounting_number(-$cash_flow_data[$year - 1]['purchase_investments']));
    $html .= row('Net Cash from Investing Activities', format_accounting_number($cash_flow_data[$year]['investing_activities']), format_accounting_number($cash_flow_data[$year - 1]['investing_activities']), true, true);

    $html .= '<tr><td colspan="3" style="font-weight: bold;">Financing Activities</td></tr>';
    $html .= row('Proceeds from Issue of Share Capital', format_accounting_number($cash_flow_data[$year]['proceeds_shares']), format_accounting_number($cash_flow_data[$year - 1]['proceeds_shares']));
    $html .= row('Proceeds from Borrowings (Net)', format_accounting_number($cash_flow_data[$year]['proceeds_borrowings']), format_accounting_number($cash_flow_data[$year - 1]['proceeds_borrowings']), false, true);
    $html .= row('Net Cash from Financing Activities', format_accounting_number($cash_flow_data[$year]['financing_activities']), format_accounting_number($cash_flow_data[$year - 1]['financing_activities']), true, false);

    $html .= row('Net Increase in Cash', format_accounting_number($cash_flow_data[$year]['net_increase_in_cash']), format_accounting_number($cash_flow_data[$year - 1]['net_increase_in_cash']), true, true);
    $html .= '</tbody></table>';
    $pdf->writeHTML($html, true, false, true, false, '');

    // PAGE 6+: Notes
    $pdf->AddPage();
    $html = $html_style . '<h2>Notes to the Financial Statements</h2>';

    // Note 3: Revenue
    $html .= '<h3>Note 3: Revenue</h3><p>Revenue represents invoiced sales and services, net of VAT.</p>';
    $html .= '<table cellpadding="5"><thead><tr><th width="70%">Description</th><th width="30%">Amount</th></tr></thead><tbody>';
    $html .= row('Sales / Services', format_accounting_number($summary_data[$year]['total_revenue']), '', false, false);
    $html .= '</tbody></table>';

    // Note 4: Expenses
    $html .= '<h3>Note 4: Operating Expenses</h3>';
    $breakdown = $summary_data[$year]['expense_breakdown'] ?? [];
    $html .= '<table cellpadding="5"><thead><tr><th width="70%">Description</th><th width="30%">Amount</th></tr></thead><tbody>';
    if (!empty($breakdown['cogs'])) {
        $html .= '<tr><td colspan="2" style="font-weight:bold;">Cost of Sales</td></tr>';
        foreach ($breakdown['cogs'] as $name => $amt) $html .= row('- ' . htmlspecialchars(ucwords(str_replace('_',' ',$name))), format_accounting_number($amt), '');
    }
    if (!empty($breakdown['opex'])) {
        $html .= '<tr><td colspan="2" style="font-weight:bold;">Administrative Expenses</td></tr>';
        foreach ($breakdown['opex'] as $name => $amt) $html .= row('- ' . htmlspecialchars(ucwords(str_replace('_',' ',$name))), format_accounting_number($amt), '');
    }
    $html .= '</tbody></table>';

    // Note 6: PPE Movement
    $html .= '<h3>Note 6: Property, Plant and Equipment (Movement Schedule)</h3>';
    if (!empty($ppe_movement[$year])) {
        $html .= '<table cellpadding="5"><thead><tr><th width="20%">Category</th><th width="16%">Opening Cost</th><th width="16%">Additions</th><th width="16%">Dep. Charge</th><th width="16%">Accum. Dep.</th><th width="16%">Net Book Value</th></tr></thead><tbody>';
        foreach ($ppe_movement[$year] as $cat => $d) {
             $html .= '<tr>
                <td style="border:1px solid #e5e7eb;">'.$cat.'</td>
                <td style="border:1px solid #e5e7eb;text-align:right;">'.format_accounting_number($d['opening_cost']).'</td>
                <td style="border:1px solid #e5e7eb;text-align:right;">'.format_accounting_number($d['additions']).'</td>
                <td style="border:1px solid #e5e7eb;text-align:right;">'.format_accounting_number($d['charge_for_year']).'</td>
                <td style="border:1px solid #e5e7eb;text-align:right;">'.format_accounting_number($d['closing_accum_dep']).'</td>
                <td style="border:1px solid #e5e7eb;text-align:right;font-weight:bold;">'.format_accounting_number($d['closing_nbv']).'</td>
             </tr>';
        }
        $html .= '</tbody></table>';
    } else {
        $html .= '<p>No PPE assets recorded.</p>';
    }

    // Note 7: Investments
    $html .= '<h3>Note 7: Financial Assets at Fair Value (FVTPL)</h3>';
    $html .= '<p><i>Investments are measured at fair value through profit or loss.</i></p>';
    if (!empty($investment_details)) {
        $html .= '<table cellpadding="5"><thead><tr><th width="40%">Description</th><th width="30%">Type</th><th width="30%">Value</th></tr></thead><tbody>';
        foreach ($investment_details as $inv) {
            $html .= '<tr><td style="border:1px solid #e5e7eb;">' . htmlspecialchars($inv['description']) . '</td><td style="border:1px solid #e5e7eb;">' . htmlspecialchars($inv['investment_type']) . '</td><td style="border:1px solid #e5e7eb;text-align:right;">' . format_accounting_number($inv['purchase_cost']) . '</td></tr>';
        }
        $html .= '</tbody></table>';
    } else { $html .= '<p>No financial investments.</p>'; }

    // Note 8: Equity
    $html .= '<h3>Note 8: Equity & Share Capital</h3>';
    $eq = $equity_data[$year];
    $html .= '<p><b>Share Capital:</b> ' . format_accounting_number($eq['share_capital']) . '</p>';
    $html .= '<p><b>Retained Earnings:</b> ' . format_accounting_number($eq['retained_earnings']) . '</p>';
    if ($manual_inputs['number_of_shares'] > 0) {
        $html .= '<p>The capital injection of ' . format_accounting_number($manual_inputs['share_capital']) . ' represents the allotment of ' . number_format($manual_inputs['number_of_shares']) . ' Ordinary Shares at a par value of ' . format_accounting_number($manual_inputs['par_value']) . ' each to ' . htmlspecialchars($shareholder_name) . '.</p>';
    }

    $pdf->writeHTML($html, true, false, true, false, '');

    $pdf->Output('Financial_Statement_' . $year . '.pdf', 'I');

} catch (Throwable $e) {
    http_response_code(500);
    echo "<h1>Error Generating Report</h1>";
    echo "<p>" . htmlspecialchars($e->getMessage()) . "</p>";
    echo "<pre>" . htmlspecialchars($e->getTraceAsString()) . "</pre>";
}

function format_accounting_number($number, $decimals = 2) {
    if (floatval($number) == 0) return '-';
    if ($number < 0) return '(' . number_format(abs($number), $decimals) . ')';
    return number_format($number, $decimals);
}
?>
